#define DEF_EVOLUTION_VERSION_TAG "unknown"
#define DEF_EVOLUTION_VERSION "0.1.0.6"
#define DEF_EVOLUTION_RELEASE_NAME "Bloody"
#define DEF_EVOLUTION_VERSION_FULL DEF_EVOLUTION_VERSION "-" DEF_EVOLUTION_VERSION_TAG
#define DEF_EVOLUTION_VERSION_IS_RELEASE false

#include "version.h"

const char* const EVOLUTION_VERSION_TAG = DEF_EVOLUTION_VERSION_TAG;
const char* const EVOLUTION_VERSION = DEF_EVOLUTION_VERSION;
const char* const EVOLUTION_RELEASE_NAME = DEF_EVOLUTION_RELEASE_NAME;
const char* const EVOLUTION_VERSION_FULL = DEF_EVOLUTION_VERSION_FULL;
const bool EVOLUTION_VERSION_IS_RELEASE = DEF_EVOLUTION_VERSION_IS_RELEASE;
